# Generated by Django 4.0.5 on 2022-06-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa', 'Akwa'), ('Ibom', 'Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross', 'Cross'), ('River', 'River'), ('Delta', 'Delta'), ('Eb   onyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=40)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('ratings', models.IntegerField(choices=[(4, 4), (5, 5), (0, 0), (1, 1), (3, 3), (2, 2)])),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveling_mode', models.CharField(choices=[('Road', 'Road'), ('Air', 'Air'), ('Train', 'Train')], max_length=59)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reserved_seats', models.IntegerField()),
                ('car_type', models.CharField(choices=[('Bus', '18 Seaters'), ('Mini Car', '4 Seaters'), ('Car', '6 Seaters')], default=1, max_length=50)),
                ('price', models.FloatField(editable=False)),
                ('paid', models.BooleanField(default=False)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='Travel.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='Travel.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lugage_policy', models.TextField()),
                ('park', models.ManyToManyField(to='Travel.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransportPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Bus', '18 Seaters'), ('Mini Car', '4 Seaters'), ('Car', '6 Seaters')], default=1, max_length=100)),
                ('price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.transportcompany')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_loc', to='Travel.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_loc', to='Travel.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tx_signed_val', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed'), ('None', 'None')], default='None', max_length=20, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.FloatField()),
                ('travel_option', models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], max_length=30)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Travel.location')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='transport_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel.transportcompany'),
        ),
    ]
