# Generated by Django 4.0.5 on 2022-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0003_alter_ticket_car_type_alter_transportprice_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='car_type',
            field=models.CharField(choices=[('Car', '6 Seaters'), ('Mini Car', '4 Seaters'), ('Bus', '18 Seaters')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='transportprice',
            name='car_type',
            field=models.CharField(choices=[('Car', '6 Seaters'), ('Mini Car', '4 Seaters'), ('Bus', '18 Seaters')], default=1, max_length=100),
        ),
    ]
