# Generated by Django 4.0.5 on 2022-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_alter_ticket_car_type_alter_transportprice_car_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='car_type',
            field=models.CharField(choices=[('Car', '6 Seaters'), ('Bus', '18 Seaters'), ('Mini Car', '4 Seaters')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='transportprice',
            name='car_type',
            field=models.CharField(choices=[('Car', '6 Seaters'), ('Bus', '18 Seaters'), ('Mini Car', '4 Seaters')], default=1, max_length=100),
        ),
    ]
